spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phoneshop
    username: phoneshop
    password: heng
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # This will automatically update your schema if needed
    show-sql: true  # Optional: To log SQL queries in the console for debugging
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true  # Optional: To pretty-print the SQL for readability
        use_sql_comments: true  # Optional: To include SQL comments in logs
